# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/bedard/badpermissions/models/category/fields.yaml

# Model Class name
modelClass: Bedard\BadPermissions\Models\Category

# Default redirect location
defaultRedirect: bedard/badpermissions/categories

# Create page
create:
    title: Create Category
    redirect: bedard/badpermissions/categories/update/:id
    redirectClose: bedard/badpermissions/categories

# Update page
update:
    title: Edit Category
    redirect: bedard/badpermissions/categories
    redirectClose: bedard/badpermissions/categories

# Preview page
preview:
    title: Preview Category